declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_API_URL?: string;
    EXPO_PUBLIC_E2E?: string;
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_IOS_URL_SCHEME?: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
    EXPO_PUBLIC_IAP_ANDROID_MONTHLY_BASE_PLAN_ID?: string;
    EXPO_PUBLIC_IAP_ANDROID_MONTHLY_PRODUCT_ID?: string;
    EXPO_PUBLIC_IAP_ANDROID_PACKAGE_NAME?: string;
    EXPO_PUBLIC_IAP_ANDROID_YEARLY_BASE_PLAN_ID?: string;
    EXPO_PUBLIC_IAP_ANDROID_YEARLY_PRODUCT_ID?: string;
    EXPO_PUBLIC_IAP_IOS_MONTHLY_PRODUCT_ID?: string;
    EXPO_PUBLIC_IAP_IOS_YEARLY_PRODUCT_ID?: string;
  }
}
