services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: serch
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-54329}:5432"
    volumes:
      - postgres_18_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d serch"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres_test:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: serch_test
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    ports:
      - "127.0.0.1:${POSTGRES_TEST_PORT:-54330}:5432"
    volumes:
      - postgres_18_test_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d serch_test"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_18_data:
  postgres_18_test_data:
